### PR TITLE
Implement a few new configuration options

### LINKED ISSUE #70: make max concurrent runs for etl jobs a configuration value
right now we hard code all `Job` resources to have a max number of concurrent runs of 5. This number came from nowhere special and to really know what to set it at long term we will need usage metrics. In the short term, we should make it a configuration value in the ETL config so it's at least easy to change quickly.

### LINKED ISSUE #71: allow prefix to be specified for data crawler paths
right now we only crawl a bucket (all prefixes) in a single way. we will eventually want the ability to have a crawler operate only on a specific prefix (directory path) in an s3 bucket.

This may be as simple as adding a prefix arg (default of `None`) to the `DataCrawler` resource and appending it to the bucket path (if it's not `None`) to the `CrawlerS3TargetArgs.path` value when creating the crawler.

### PR DESCRIPTION
**Pull request by mehalter**
Closes #71, Closes #70

This is just taking some time to implement some of the outstanding issues while waiting on new permissions!

### CODE REVIEW

**Comment by thecaffiend** [comment]
code looks fine, but can we add `max_concurrent_runs` (even set tot he default of 5) to the config file as well so we have an example in there and so it gets put into the public config file as well?

**Comment by mehalter** [comment]
It's in there @thecaffiend no?

**Comment by thecaffiend** [comment]
lol. i can't read a file tree...

**Review by thecaffiend — APPROVED** [review]
MTGL

**Pull request merged**
